import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";
import questionData from "../public/data.json";
import { IoLogoGithub } from "react-icons/io";
import ThemeChanger from "../components/ThemeChanger";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DSA 375</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen flex flex-col items-center p-10">
        <div className="title-container text-3xl">DSA 375</div>
        <div className="text-sm">By Aman & Shradha</div>
        <div className="cards-container mt-10 md:mt-12 flex flex-row flex-wrap justify-center gap-10">
          {questionData.map((topic, index) => {
            return (
              <Card
                topic={topic.topic}
                title={topic.title}
                key={index}
                qty={topic.problems.length}
              />
            );
          })}
        </div>
      </main>
      <footer className="w-screen flex flow-row justify-center my-10 items-center gap-10">
        <ThemeChanger />
        <a
          href="https://github.com/krsambhav/DSA-375/"
          target={"_blank"}
          rel="noreferrer"
        >
          <IoLogoGithub className="text-2xl" />
        </a>
      </footer>
    </div>
  );
};

export default Home;
